### ISSUE TITLE
ImportError: IPython version 6 is not supported.

### ISSUE THREAD

**Issue by ysshah** [pl31/heroku-jupyter#14]
Hello, when I pushed the "Deploy to Heroku" button and set a password, I got an Application Error after everything was done building. Here are the logs:
```
2017-04-25T00:26:02.260675+00:00 app[web.1]: Enabling: jupyter_nbextensions_configurator
2017-04-25T00:26:02.261040+00:00 app[web.1]: - Writing config: /app/.jupyter
2017-04-25T00:26:02.261373+00:00 app[web.1]:     - Validating...
2017-04-25T00:26:02.261549+00:00 app[web.1]:       jupyter_nbextensions_configurator  [32mOK[0m
2017-04-25T00:26:02.261689+00:00 app[web.1]: Enabling notebook nbextension nbextensions_configurator/config_menu/main...
2017-04-25T00:26:02.263585+00:00 app[web.1]: Enabling tree nbextension nbextensions_configurator/tree_tab/main...
2017-04-25T00:26:04.256027+00:00 app[web.1]: Traceback (most recent call last):
2017-04-25T00:26:04.256033+00:00 app[web.1]:   File "/app/.jupyter/jupyter_notebook_config.py", line 6, in <module>
2017-04-25T00:26:04.256034+00:00 app[web.1]:     import pgcontents
2017-04-25T00:26:04.256035+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/pgcontents/__init__.py", line 14, in <module>
2017-04-25T00:26:04.256035+00:00 app[web.1]:     from .checkpoints import PostgresCheckpoints
2017-04-25T00:26:04.256038+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/pgcontents/checkpoints.py", line 6, in <module>
2017-04-25T00:26:04.256039+00:00 app[web.1]:     from .api_utils import (
2017-04-25T00:26:04.256040+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/pgcontents/api_utils.py", line 16, in <module>
2017-04-25T00:26:04.256040+00:00 app[web.1]:     from .utils.ipycompat import reads, writes
2017-04-25T00:26:04.256041+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/pgcontents/utils/ipycompat.py", line 9, in <module>
2017-04-25T00:26:04.256042+00:00 app[web.1]:     raise ImportError("IPython version %d is not supported." % IPY_MAJOR)
2017-04-25T00:26:04.256043+00:00 app[web.1]: ImportError: IPython version 6 is not supported.
2017-04-25T00:26:04.457704+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-25T00:26:04.447572+00:00 heroku[web.1]: Process exited with status 255
```
It seems that the cause is `ImportError: IPython version 6 is not supported.` How can I fix this?

**Comment by pl31** [comment]
IPython 6 was released a few days ago. The notebook store pgcontents needs to be updated. I opened an issue here: quantopian/pgcontents#28

**Comment by pl31** [comment]
IPython 6 is supported, now. Still a deployed noteboook does not run due to #38.
